### ISSUE TITLE
Screenshots needed for publication

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-ac-virtual-lab#4]
For https://github.com/phetsims/qa/issues/752

@samreid the sim needs screenshots before publication. I'll take care of them soon and commit to master and the release branch.

**Comment by arouinfar** [comment]
@samreid I'm unable to use the GitHub interface to commit the screenshots because the assets directory doesn't exist yet. I tried making the commit from my local copy but run into this error:

```
/Users/rouinfar/Documents/PhET/HTML5_Sims/perennial/js/scripts/hook-pre-commit.js:25
( async () => {
        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
 ```   
 
 @samreid can you take care of the commits? Here are the assets:
[circuit-construction-kit-ac-virutal-lab-screenshot.png](https://user-images.githubusercontent.com/8419308/145735564-25fe61d0-c914-4853-beed-efefecbfc8cc.png)
[circuit-construction-kit-ac-virutal-lab-screenshot-alt1.png](https://user-images.githubusercontent.com/8419308/145735558-3bf9129d-c1e7-4e83-8ab6-5554c08c1367.png)
[circuit-construction-kit-ac-virutal-lab-screenshot-alt2.png](https://user-images.githubusercontent.com/8419308/145735561-19f7db6c-0335-4086-8e3a-4ad83ccc1dbf.png)
[circuit-construction-kit-ac-virutal-lab-screenshot-alt3.png](https://user-images.githubusercontent.com/8419308/145735563-ab1d592f-456f-4ddc-bc92-ee28030d0886.png)

**Comment by arouinfar** [comment]
Actually, it looks like the naive approach of dragging/dropping the entire assets directory might actually work. I'll take care of it myself @samreid and let you know if I run into issues.

**Comment by arouinfar** [comment]
Aside from accidentally committing the screenshots to the QA repo (and subsequently deleting it), things appear to have worked. @samreid can you please review?

**Comment by samreid** [comment]
I fixed a typo in AC-virtual lab in master, and cherry picked it to the 1.0 branch. @arouinfar can you please double check the change?

**Comment by arouinfar** [comment]
Good catch @samreid. Thanks for fixing the typo. The screenshots look good, closing.
